### ISSUE TITLE
Корректное отображение при разном масштабе

### ISSUE THREAD

**Issue by realnumberboi** [maksimil/luna_test#10]
- [ ] выровнять карточки по центру, вне зависимости от масштаба // _при изменении масштаба высота не фиксирована из-за чего карточки плющатся_
~- [ ] исправить белое мерцание в слайдере при скролле снизу вверх // _в сафари оно всё ещё есть_~

![image](https://user-images.githubusercontent.com/28487425/202516642-41c2a2b4-e9e1-4256-b8a0-cc1c368204ab.png)

**Comment by demig00d** [comment]
- [ ] выровнять карточки по центру, вне зависимости от масштаба // _при изменении масштаба высота не фиксирована из-за чего карточки плющатся_
- [ ] исправить белое мерцание в слайдере при скролле снизу вверх // _в сафари оно всё ещё есть_

**Comment by maksimil** [comment]
Я не уверен в том, как можно исправить мерцание, я даже увидеть его не могу, тк у меня safari нет

**Comment by demig00d** [comment]
[swiper/react](https://github.com/nolimits4web/swiper) - слайдер у нас этой библиотекой реализован?
Если да, то там есть разные issues с ключевыми словами flickering и safari

**Comment by demig00d** [comment]
[коммит](https://github.com/maksimil/luna_test/commit/b8e6d4369d71960d4cf0a6505fb8d8d2027aef0c) не решил проблему с масштабом, попробуй сравнить к примеру с https://vakhtangov.ru/

**Comment by maksimil** [comment]
> @maksimil слайдер у нас [этой библиотекой](https://github.com/nolimits4web/swiper) реализован? Если да, то там есть разные issues с ключевыми словами flickering и safari
> 
> возможно там есть и workaround

workaround в [коммите](https://github.com/maksimil/luna_test/commit/d55feaf25676765491d6e477ee6f644b66024d6a). Проверь, сработало ли, пожалуйста.

**Comment by demig00d** [comment]
> > @maksimil слайдер у нас [этой библиотекой](https://github.com/nolimits4web/swiper) реализован? Если да, то там есть разные issues с ключевыми словами flickering и safari
> > возможно там есть и workaround
> 
> workaround в [коммите](https://github.com/maksimil/luna_test/commit/d55feaf25676765491d6e477ee6f644b66024d6a). Проверь, сработало ли, пожалуйста.

так же((( 
https://user-images.githubusercontent.com/28487425/202528813-98a05c20-d411-47ce-abde-7002e1c4b37c.mp4

**Comment by maksimil** [comment]
Ты точно перезагрузил без кэша (ctrl+r)?, у меня иногда с этим проблемы связаны при разработке

**Comment by demig00d** [comment]
> Ты точно перезагрузил без кэша (ctrl+r)?, у меня иногда с этим проблемы связаны при разработке

перезапустил, изменений нет

**Comment by demig00d** [comment]
ладно, предлагаю вынести в отдельный issues и оставить до лучших времён

**Comment by demig00d** [comment]
так же думаю что масштаб стоит делать после дизайна (#11), потому что элемента  там отличаются
