### ISSUE TITLE
Новый дизайн

### ISSUE THREAD

**Issue by realnumberboi** [maksimil/luna_test#11]
Применить новый дизайн (https://www.figma.com/file/xockMwJFRcDaGT5c9B0nmO/Luna-Main?node-id=0%3A1&t=UgUDS1XHWYMSqOEC-0), сайт должен выглядеть как на макете вне зависимости от масштаба, иконка луны под датой пока не объязательна

**Comment by demig00d** [comment]
разбил на подзадачи:

- [x] https://github.com/maksimil/luna_test/issues/19
- [x] https://github.com/maksimil/luna_test/issues/20
- [x] https://github.com/maksimil/luna_test/issues/21
- [x] https://github.com/maksimil/luna_test/issues/23
